remote_theme: pages-themes/minimal@master
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lifetime learner.
logo: /assets/img/logo.png
description: Fig.1 - An ordinary person with AI-generated cartoon-esque selfie.
